name: Clear Translated Titles Database Files
on:
  workflow_call:
  workflow_dispatch:
jobs:
  clear-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.0
        with:
          ref: output
      - name: Clear Files
        run: |
          > titles.db
      - name: Pushing to output
        run: |
          git config --global user.name "github-actions [BOT]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add titles.db
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update titles.db files via GitHub Actions"
            git push origin output
          fi
