name: Force Send Mail
on:
  workflow_dispatch:
jobs:
  reset-hash:
    uses: hexros-dev/check-livestreams/.github/workflows/reset.yml@master
  run-script:
    needs: reset-hash
    uses: hexros-dev/check-livestreams/.github/workflows/python_script.yml@master
    secrets: inherit
