name: Run Python Script
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.0
        with:
          ref: master
      - name: Set Up Python
        uses: actions/setup-python@v5.2.0
        with:
          python-version: "3.12.6"
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Python Script
        env:
          SENDER_EMAIL: ${{secrets.SENDER_EMAIL}}
          SENDER_PWD: ${{secrets.SENDER_PWD}}
          RECEIVER_EMAIL: ${{secrets.RECEIVER_EMAIL}}
        run: |
          python main.py
      - name: Pushing to master
        run: |
          git config --global user.name "github-actions [BOT]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          SHORT_SHA = $(echo "${GITHUB_SHA}" | cut -c1-7)
          git commit -m "[$SHORT_SHA] Update prev_hash.md5 file via GitHub Actions"
          git push origin master
