name: Run Python Script
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Set TERM environment variable
        run: echo "TERM=xterm" >> $GITHUB_ENV
      - name: Checkout Repository
        uses: actions/checkout@v4.2.0
        with:
          ref: master
      - name: Set Up Python
        uses: actions/setup-python@v5.2.0
        with:
          python-version: "3.12.6"
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -q
      - name: Run Python Script
        env:
          SENDER_EMAIL: ${{secrets.SENDER_EMAIL}}
          SENDER_PWD: ${{secrets.SENDER_PWD}}
          RECEIVER_EMAIL: ${{secrets.RECEIVER_EMAIL}}
        run: |
          python main.py
      - uses: actions/upload-artifact@v4
        with:
          name: _code_
  push-code:
    runs-on: ubuntu-latest
    needs: [run-script]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: _code_
      - name: Pushing to master
        run: |
          git config --global user.name "github-actions [BOT]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update prev_hash.md5 file via GitHub Actions"
            git push origin master
          fi
