name: Run Python Script
on:
  push:
    branches: ["master", "output"]
  pull_request:
    branches: ["master", "output"]
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
  workflow_call:
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Set TERM environment variable
        run: echo "TERM=xterm" >> $GITHUB_ENV
      - name: Checkout Repository
        uses: actions/checkout@v4.2.0
      - run: |
          git checkout master
          git checkout output
      - name: Set Up Python
        uses: actions/setup-python@v5.2.0
        with:
          python-version: "3.12.6"
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt -q
      - name: Run Python Script
        env:
          SENDER_EMAIL: ${{secrets.SENDER_EMAIL}}
          SENDER_PWD: ${{secrets.SENDER_PWD}}
          RECEIVER_EMAIL: ${{secrets.RECEIVER_EMAIL}}
        run: |
          python main.py
      - name: Pushing to master
        run: |
          git config --global user.name "github-actions [BOT]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b output || git checkout output
          git add upcoming.json live_streams.json prev_hash_live.md5 prev_hash_upcoming.md5
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update files via GitHub Actions"
            git push origin output
          fi
