name: Clear Hash Files
on:
  workflow_call:
  workflow_dispatch:
jobs:
  clear-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.0
        with:
          ref: master
      - name: Clear Files
        run: |
          > prev_hash_live.md5
          > prev_hash_upcoming.md5
      - name: Pushing to master
        run: |
          git config --global user.name "github-actions [BOT]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update hash files via GitHub Actions"
            git push origin master
          fi
